- name: Change user password
  # ========================================================
  # Allows caller to override hosts using '-e cmd_hosts='
  hosts: "{{ cmd_hosts | default('jupyterhub') }}"
  become: true

  roles:
    - change_password_user
#
# ========================================================
# sudo ansible-playbook playbooks/change_password_user.yml -i inventories/cassiopee/hosts.ini --extra-vars "username=foo password=bar"

