- name: Remove user access
  # ========================================================
  # Allows caller to override hosts using '-e cmd_hosts='
  hosts: "{{ cmd_hosts | default('jupyterhub') }}"
  become: "{{ cmd_become | default('true') }}"
  ignore_errors: "{{ cmd_ignore_errors | default('false') }}"

  roles:
    - remove_user
#
# ========================================================
# ansible-playbook playbooks/remove_user.yml -i inventories/cassiopee/hosts.ini --extra-vars "username=foo"
