- name: Restart JupyterHub
  # ========================================================
  hosts: "{{ cmd_hosts | default('jupyterhub') }}"
  become: "{{ cmd_become | default('true') }}"
  ignore_errors: "{{ cmd_ignore_errors | default('false') }}"

  roles:
    - restart
#
# ========================================================
# ansible-playbook playbooks/restart.yml -i inventories/cassiopee/hosts.ini
