---
- name: JupyterHub | package | Ensure the APT cache is up to date
  apt:
    update_cache: yes
  changed_when: False
  when: ansible_os_family == "Debian"

- name: JupyterHub | package | Install {{ ansible_os_family }} specific packages
  package:
    name: "{{ item }}"
  with_items: "{{ os_family_specific_pre }}"
  register: install_specific_result
  until: install_specific_result is success
  retries: 5
  delay: 5

- name: JupyterHub | package | Add debian backports
  apt_repository:
    repo: "deb http://ftp.debian.org/debian {{ ansible_lsb.codename }}-backports main"
    state: present
    update_cache: yes
  when: ansible_distribution in ['Debian']

- name: JupyterHub | package | Upgrade systemd on debian
  apt:
    name: systemd
    state: latest
    default_release: "{{ ansible_lsb.codename }}-backports"
  when: ansible_distribution in ['Debian']
  tags:
    # Need latest, systemd v215 is really old and a pain to support alongside newer versions
    - skip_ansible_lint

- name: JupyterHub | package | Install required packages
  package:
    name: "{{ item }}"
  with_items: "{{ required_packages }}"
  register: install_required_result
  until: install_required_result is success
  retries: 5
  delay: 5
  tags:
    - skip_ansible_lint

- name: JupyterHub | package | Install pexpect via pip
  pip:
    name: "pexpect"
    version: "3.3"

- name: JupyterHub | package | Install configurable-http-proxy
  npm:
    name: configurable-http-proxy
    global: true

- name: JupyterHub | package | Setup venv for JupyterHub
  shell: python3 -m venv /opt/jupyterhub
  args:
    creates: /opt/jupyterhub/bin/python

- name: JupyterHub | package | Install JupyterHub
  pip:
    name:
      - wheel
      - jupyterhub
      - jupyterlab
      - ipywidgets
    virtualenv: /opt/jupyterhub

- name: JupyterHub | package | Get conda gpg key
  shell: curl -s https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc | gpg --dearmor > /tmp/conda-key.gpg
  args:
    creates: /tmp/conda-key.gpg

- name: JupyterHub | package | Install conda gpg key
  shell: install -o root -g root -m 644 /tmp/conda-key.gpg /etc/apt/trusted.gpg.d/

- name: JupyterHub | package | Add conda repository
  shell: echo "deb [arch=amd64] https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main" > /etc/apt/sources.list.d/conda.list

- name: JupyterHub | package | Install conda
  apt:
    name: conda
    update_cache: true
    state: latest
